### ISSUE TITLE
Peirates unable to read secrets

### ISSUE THREAD

**Issue by sshayb** [inguardians/peirates#1]
This is the error that I am getting when trying to list the pods:

Peirates:>#
3

[+] Printing a list of Pods in this namespace......
error: unable to read certificate-authority /run/secrets/kubernetes.io/serviceaccount/ca.crt for  due to open /run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory

The service account secrets are actually located in /var/run/secrets/... Should the path be made configurable?

(Peirates version v1.0.20)

**Comment by JayBeale** [comment]
Thank you -- I've updated the path to /var/run/secrets, realizing that both /var/run/secrets and /run/secrets work in our test clusters. We could certainly make the path configurable if we hear of a cluster in the wild for which /var/run/secrets doesn't work. If you'd like, submit a pull request that creates a --svc-account-mount-path command-line flag.

**Comment by sshayb** [comment]
That works, thank you!
